version: '3.8'

services:
  my-project-database-service:
    image: 'postgres'
    container_name: 'postgresql-db-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 2345:5432

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
#    container_name: 'keycloak-service-container'
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin_password
    command:
      - start-dev
      - --http-relative-path=/auth
    ports:
      - 8080:8080
      - 8843:8843
    depends_on:
      - keycloak-db

  keycloak-db:
    image: 'postgres:16'
    container_name: 'keycloak-db-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 3345:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: