version: '3.8'

services:
  my-project-database-service:
    image: 'postgres'
    container_name: 'postgresql-db-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 2345:5432